<?php 

for($c=0;$c<sizeof($dpercent);$c++){
	
	$queryunit = "select * from routes where unit = '$dunit[$c]' and type = '2'";
	$resultunit = mysqli_query($con, $queryunit);
	$rowunit = mysqli_fetch_array($resultunit);
		
	$queryuser = "select * from workers where code = '$rowunit[worker]'";
	$resultuser = mysqli_query($con, $queryuser);
	$rowuser = mysqli_fetch_array($resultuser);
		
	$emails.= $rowuser['email'].","; 
		
}

$to  = 'jairovargasg@gmail.com';   
$subject = 'Reestablecimiento de Contraseña | Casa Pellas';
$message = '<html>
<head>
<meta charset="UTF-8">
<title>Casa Pellas</title>

<style type="text/css">
<!--
body,td,th {
	color: #223460;
	font-family: Georgia, Times New Roman, Times, serif;
}
body {
	background-color: #e88039;
	margin-top: 0px;
}

-->
</style></head>
<body>
<table width="730" align="center" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF">
	
	<tr>
		<td valign="top" bgcolor="#555555"
 style="
 padding:10px 60px;
 font-family:Arial, Helvetica, sans-serif;
 vertical-align:middle;
 font-weight:none;
 font-size:13px;
 line-height:18px;
 color:#333;"><p>Estimado Usuario,</p>
	    <p>Para reestablecer su contraseña usted deberá de hacer click en la dirección que aparece a continuación o bien copiar el siguiente link y pegarlo en su navegador de preferencia.</p>
	    <p><a href="http://pagoscp.com/password-reset.php?token='.$token.'">http://pagoscp.com/password-reset.php?token='.$token.'</a></p>
      <p><a href="http://casapellas.com/" style="text-decoration:none; color:#e88039;">www.casapellas.com</a></p></td>
 </tr>
	<tr>
		<td bgcolor="#FFFFFF"
 style="
 padding:10px 60px;
 vertical-align:middle;
 font-weight:none;
 font-family:Arial, Helvetica, sans-serif;
 border-top:1px; border-top-style:solid; border-top-color:#ededed;
 font-size:10px;
 color:#333;" >This email has been automatically generated by MultiTech Smart Solutions. Any problem please report it to info@multitechsmartsolutions.com</td>
 </tr>
</table>
</body>
</html>';
$headers  = 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
$headers .= 'To: Uusario <'.$email.'>' . "\r\n";
$headers .= 'From: Recuperacion de Contraseñas <recuperaciones@casapellas.com>' . "\r\n";
mail($to, $subject, $message);  

?>